/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false worker/cloudflare-runtime.d.ts` (hash: 2fa748b87260c447b07e406da2be4129)
interface __BaseEnv_Env {
	DB: D1Database;
	ASSETS: Fetcher;
	APP_TIMEZONE: "Europe/Berlin";
	GOOGLE_SPREADSHEET_ID: "1XmfVLnebQ7NdLV2qh2nJ_qgPQPIQdqkgw178ZfCyyuY";
	GOOGLE_SHEET_URL: "https://docs.google.com/spreadsheets/d/1XmfVLnebQ7NdLV2qh2nJ_qgPQPIQdqkgw178ZfCyyuY/edit";
	GOOGLE_CLIENT_EMAIL: string;
	GOOGLE_PRIVATE_KEY: string;
	GEMINI_API_KEY: string;
	GEMINI_BASE_URL: string;
	GEMINI_MODEL: string;
	GROQ_API_KEY: string;
	GROQ_BASE_URL: string;
	GROQ_SPEECH_MODEL: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "APP_TIMEZONE" | "GOOGLE_SPREADSHEET_ID" | "GOOGLE_SHEET_URL" | "GOOGLE_CLIENT_EMAIL" | "GOOGLE_PRIVATE_KEY" | "GEMINI_API_KEY" | "GEMINI_BASE_URL" | "GEMINI_MODEL" | "GROQ_API_KEY" | "GROQ_BASE_URL" | "GROQ_SPEECH_MODEL">> {}
}
