/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false worker/cloudflare-runtime.d.ts` (hash: 3f71995a39ecab05aa7176f374f182bd)
interface __BaseEnv_Env {
	DB: D1Database;
	AI: Ai;
	ASSETS: Fetcher;
	APP_TIMEZONE: "Europe/Berlin";
	GOOGLE_SPREADSHEET_ID: "1XmfVLnebQ7NdLV2qh2nJ_qgPQPIQdqkgw178ZfCyyuY";
	GOOGLE_SHEET_URL: "https://docs.google.com/spreadsheets/d/1XmfVLnebQ7NdLV2qh2nJ_qgPQPIQdqkgw178ZfCyyuY/edit";
	WORKERS_AI_MODEL: "@cf/meta/llama-3.3-70b-instruct-fp8-fast";
	WORKERS_AI_VISION_MODEL: "@cf/meta/llama-4-scout-17b-16e-instruct";
	GROQ_BASE_URL: "https://api.groq.com/openai/v1";
	GROQ_MODEL: "qwen/qwen3.6-27b";
	GOOGLE_CLIENT_EMAIL: string;
	GOOGLE_PRIVATE_KEY: string;
	FREEMODEL_API_KEY: string;
	FREEMODEL_BASE_URL: string;
	FREEMODEL_MODEL: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "APP_TIMEZONE" | "GOOGLE_SPREADSHEET_ID" | "GOOGLE_SHEET_URL" | "WORKERS_AI_MODEL" | "WORKERS_AI_VISION_MODEL" | "GROQ_BASE_URL" | "GROQ_MODEL" | "GOOGLE_CLIENT_EMAIL" | "GOOGLE_PRIVATE_KEY" | "FREEMODEL_API_KEY" | "FREEMODEL_BASE_URL" | "FREEMODEL_MODEL">> {}
}
