/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false worker/cloudflare-runtime.d.ts` (hash: 2737ab068adc53ffff5375f1489b7396)
interface __BaseEnv_Env {
	BACKUPS: KVNamespace;
	DB: D1Database;
	LOGIN_RATE_LIMITER: RateLimit;
	ASSETS: Fetcher;
	APP_TIMEZONE: "Europe/Berlin";
	GOOGLE_SPREADSHEET_ID: "1XmfVLnebQ7NdLV2qh2nJ_qgPQPIQdqkgw178ZfCyyuY";
	GOOGLE_SHEET_URL: "https://docs.google.com/spreadsheets/d/1XmfVLnebQ7NdLV2qh2nJ_qgPQPIQdqkgw178ZfCyyuY/preview";
	GEMINI_BASE_URL: "https://generativelanguage.googleapis.com/v1beta";
	GEMINI_MODEL: "gemini-flash-latest";
	GROQ_BASE_URL: "https://api.groq.com/openai/v1";
	GROQ_SPEECH_MODEL: "whisper-large-v3-turbo";
	APP_PIN: string;
	GOOGLE_CLIENT_EMAIL: string;
	GOOGLE_PRIVATE_KEY: string;
	GEMINI_API_KEY: string;
	GROQ_API_KEY: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "APP_TIMEZONE" | "GOOGLE_SPREADSHEET_ID" | "GOOGLE_SHEET_URL" | "GEMINI_BASE_URL" | "GEMINI_MODEL" | "GROQ_BASE_URL" | "GROQ_SPEECH_MODEL" | "APP_PIN" | "GOOGLE_CLIENT_EMAIL" | "GOOGLE_PRIVATE_KEY" | "GEMINI_API_KEY" | "GROQ_API_KEY">> {}
}
